web_extractor:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  min_line_length: 30
  crawling:
    max_depth: 2  # How deep to crawl
    max_pages_per_domain: 10  # Maximum pages to crawl per domain
    include_subdomains: true  # Whether to crawl subdomains
    timeout: 30  # Timeout in seconds for each request
    concurrent_requests: 3  # Number of concurrent requests

qa_generator:
  model_name: "gemini-2.5-flash-preview-04-17"
  num_default_pairs: 50

fine_tuner:
  base_model: "google/flan-t5-small"
  training:
    num_train_epochs: 50.0  # Increased for better convergence
    per_device_train_batch_size: 4  # Increased as T5-small can handle it
    learning_rate: 5.0e-5  # Reduced for more stable training
    weight_decay: 0.05  # Increased for better regularization
    max_grad_norm: 1.0  # Increased to avoid too aggressive clipping
    warmup_ratio: 0.1  # Increased for more stable initial training
    lr_scheduler_type: "cosine"
    dataloader_pin_memory: false
  lora:
    r: 8  # Increased for better expressiveness
    lora_alpha: 32  # Increased for stronger adaptation
    lora_dropout: 0.05  # Reduced to prevent overfitting
    target_modules: ["q", "k", "v", "o"]  # Added more attention components
    bias: "none"
    task_type: "SEQ_2_SEQ_LM"