web_extractor:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  min_line_length: 30

qa_generator:
  model_name: "gemini-2.5-flash-preview-04-17"
  num_default_pairs: 5

fine_tuner:
  base_model: "facebook/opt-125m"
  training:
    num_train_epochs: 3.0
    per_device_train_batch_size: 4
    learning_rate: 2.0e-5
    weight_decay: 0.01
    dataloader_pin_memory: false